name: run Scheduling.py

on:
  schedule:
    - cron: '*/30 * * * *'  # Runs every 30 minutes (UTC)
  workflow_dispatch:         # Allows manual trigger from GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo content
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: ./

      - name: Execute Scheduling.py
        env:
          PRABHAT_SECRET_KEY: ${{ secrets.PRABHAT_SECRET_KEY }}
          SERVICE_ACCOUNT_JSON: ${{ secrets.SERVICE_ACCOUNT_JSON }}
        run: |
          echo "ðŸš€ Starting Scheduling.py..."
          python Scheduling.py
          echo "âœ… Scheduling.py execution complete."
        working-directory: ./
